export type UiLanguage = "ja" | "en";

export const uiStrings = {
  ja: {
    lede: "曖昧な判断を、たどり直せる構造へ。",
    languageLink: "English",
    languageHref: "/?lang=en",
    flowRegion: "会議ログの処理フロー",
    flowIntro: "会議ログを最大5テーマへ分け、判断の経緯と次の行動をMarkdownにします。",
    flowList: "会議ログからMarkdownまでの流れ",
    flowSteps: ["貼り付け", "テーマ確認", "Trace生成", "ZIP保存"],
    complete: "完了",
    current: "現在",
    modeNav: "入力モード",
    transcriptMode: "会議・文字起こし",
    memoMode: "アイデアメモ",
    transcriptTitle: "会議・文字起こしからテーマを見つける",
    transcriptIntro: "議事録や会話ログを貼り付け、最大5つの判断テーマに分けます。確認後、テーマごとのDecision Traceを生成できます。",
    transcriptLabel: "文字起こし",
    transcriptHelp: "80〜30,000文字。内容は処理のためOpenAIへ送信され、このアプリには保存されません。",
    chars: "文字",
    useTranscriptSample: "日本語サンプル議事録を使う",
    detectingStatus: "判断テーマを検出しています。",
    detectingButton: "検出中…",
    detectButton: "テーマを検出",
    memoTitle: "アイデアメモを整理する",
    memoIntro: "ひとつのアイデアや検討内容を、追跡できる6つの判断要素に整理します。",
    samples: "サンプル",
    memoLabel: "判断メモ",
    memoHelp: "決めたいこと、背景、選択肢、判断基準が分かるように80〜12,000文字で入力してください。",
    privacy: "内容は処理のためOpenAIへ送信されます。このアプリは入力内容を保存しません。",
    organizing: "判断の構造を整理しています。しばらくお待ちください。",
    generating: "生成中…",
    retry: "もう一度試す",
    generateTrace: "Decision Traceを生成",
    reviewTitle: "生成するテーマを確認",
    reviewIntro: "最大5件。不要なテーマは外し、タイトルを必要に応じて修正できます。",
    selectSuffix: "を生成対象にする",
    titleSuffix: "のタイトル",
    evidence: "根拠抜粋",
    generateSelected: (count: number) => `選択した${count}件を生成`,
    progressTitle: "テーマ別Traceを生成",
    progress: (done: number, total: number) => `${done}/${total}生成中`,
    cancelSuffix: "を中止",
  },
  en: {
    lede: "AI gives answers. Decision Trace preserves why.",
    languageLink: "日本語",
    languageHref: "/",
    flowRegion: "Meeting transcript workflow",
    flowIntro: "Split a meeting transcript into up to five decision topics, then turn the reasoning and next actions into Markdown.",
    flowList: "From meeting transcript to Markdown",
    flowSteps: ["Paste", "Review topics", "Generate traces", "Save ZIP"],
    complete: "Done",
    current: "Current",
    modeNav: "Input mode",
    transcriptMode: "Meeting transcript",
    memoMode: "Idea memo",
    transcriptTitle: "Find decisions in a meeting transcript",
    transcriptIntro: "Paste meeting minutes or a conversation log. Review up to five detected decision topics, then generate a Decision Trace for each one.",
    transcriptLabel: "Transcript",
    transcriptHelp: "80–30,000 characters. Your text is sent to OpenAI for processing and is not stored by this app.",
    chars: "characters",
    useTranscriptSample: "Use English sample transcript",
    detectingStatus: "Detecting decision topics.",
    detectingButton: "Detecting…",
    detectButton: "Detect topics",
    memoTitle: "Structure an idea memo",
    memoIntro: "Turn one idea or open question into six traceable decision elements.",
    samples: "Samples",
    memoLabel: "Decision memo",
    memoHelp: "Enter 80–12,000 characters describing the decision, context, options, and criteria.",
    privacy: "Your text is sent to OpenAI for processing. This app does not store it.",
    organizing: "Structuring the decision. Please wait.",
    generating: "Generating…",
    retry: "Try again",
    generateTrace: "Generate Decision Trace",
    reviewTitle: "Review topics to generate",
    reviewIntro: "Up to five topics. Exclude anything irrelevant and edit titles when needed.",
    selectSuffix: " — include in generation",
    titleSuffix: " title",
    evidence: "Source excerpts",
    generateSelected: (count: number) => `Generate ${count} selected ${count === 1 ? "topic" : "topics"}`,
    progressTitle: "Generate a trace for each topic",
    progress: (done: number, total: number) => `Generating ${done}/${total}`,
    cancelSuffix: " — cancel",
  },
} as const;

export type UiStrings = (typeof uiStrings)[UiLanguage];
